### ISSUE TITLE
'DataFrame' object has no attribute 'append'

### ISSUE THREAD

**Issue by jaustingeorge** [w-s-bitcoin/Bitcoin-Net-Worth-Tracker#2]
I'm getting an AttributeError: 'DataFrame' object has no attribute 'append' in cell three when running.

% pip list | grep pandas
pandas                   2.0.1

<img width="994" alt="image" src="https://github.com/w-s-bitcoin/Bitcoin-Net-Worth-Tracker/assets/11656868/c9829b3a-d91c-4c5b-8184-266738df04f7">

Any ideas?

**Comment by w-s-bitcoin** [comment]
I'm using Pandas version 1.3.5 so I'm guessing append has been deprecated in newer versions.

**Comment by jaustingeorge** [comment]
I uninstalled pandas 2.0.1
% pip uninstall pandas

And installed pandas 1.3.5
% pip install pandas==1.3.5

That got the job done. Thanks for the great code.
